### ISSUE TITLE
Future Enhancement Build Checklist

### ISSUE THREAD

**Issue by cdcabrera** [patternfly-webcomponents/patternfly-webcomponents#62]
A checklist of near future build enhancements
  - [x] Contributor Guidelines, Additional Review Requested
  - [ ] Grunt to Webpack conversion
  - [ ] Continuous Semantic Releases
  - [ ] Storybook "like" integration

Additional 
  - [ ] Research into utilizing Typescript, possibly "Typescript like" Interfaces for ECMA2015

**Comment by cdcabrera** [comment]
@priley86 just a general checklist, feel free to rearrange accordingly

**Comment by priley86** [comment]
awesome! this list looks good... i am planning to give the Storybook integration a go this week. I am hoping we can be an early beta tester of integrating Storybooks w/ WCs, and long term, potentially contribute that formally upstream. We have a nice continuous release/storybook dev build process/test page deploy process in pf-react that I would love to share in this repo. It would also be super cool to adopt Prettier if folks are onboard with it. I will likely not get to the Typescript interface research for a while, so if anyone wants to move forward on this, please feel free! I imagine it will become very useful.

**Comment by priley86** [comment]
thanks @cdcabrera !
